[package]
name = "bcr-wallet-transport"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
bcr-common = {workspace = true}
bcr-wallet-core = {workspace = true}
bcr-wallet-persistence = {workspace = true, features = ["db-redb"]}
nostr = {workspace = true}
nostr-sdk = {workspace = true, features = ["nip06", "nip59"]}
serde_json.workspace = true
thiserror.workspace = true
tokio = {workspace = true}
tracing.workspace = true
uuid = {workspace = true}
