[package]
name = "bcr-wallet-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]

serde-wasm-bindgen.workspace = true
tokio_with_wasm = "0.8.5"
wasm-bindgen = "0.2"
js-sys = "0.3"
wasm-bindgen-futures = "0.4.50"
thiserror.workspace = true
serde.workspace = true
async-trait.workspace = true
reqwest = { workspace = true, features = ["json"] }
anyhow.workspace = true
rand.workspace = true
rexie.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-wasm = "0.2.1"
getrandom = { version = "0.2.16", features = ["js"] }
# getrandom = { version = "0.3.3", features = ["wasm_js"] }
cashu = { version = "0.9.2", default-features = false, features = ["wallet"] }

[dev-dependencies]
wasm-bindgen-test = { version = "0.3" }

[lib]
crate-type = ["cdylib", "rlib"]
