[package]
name = "bcr-wallet-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bcr-wallet-lib.workspace = true
bip39.workspace = true
bitcoin.workspace = true
cashu = { workspace = true, features = ["wallet"] }
cdk = { workspace = true, features = ["wallet"] }
ciborium.workspace = true
getrandom = { version = "0.2.16", features = ["js"] }
js-sys = "0.3"
rand.workspace = true
reqwest = { workspace = true, features = ["json"] }
rexie.workspace = true
serde-wasm-bindgen.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = {workspace = true}
tokio_with_wasm = {version = "0.8", features = ["rt-multi-thread"]}
tracing-subscriber.workspace = true
tracing-wasm.workspace = true
tracing.workspace = true
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[dev-dependencies]
bcr-wdc-utils = {git = "https://github.com/BitcreditProtocol/wildcat", features = ["test-utils"]}
mockall = { workspace = true}
wasm-bindgen-test = { version = "0.3" }

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "s"
