[package]
name = "bcr-wallet-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ammonia = "4"
bcr-common = {workspace = true}
bip39.workspace = true
bitcoin.workspace = true
borsh.workspace = true
chrono = {workspace = true}
ecies.workspace = true
email_address = { version = "0.2", default-features = false }
nostr = {workspace = true}
serde.workspace = true
strum = {workspace = true, features = ["derive"]}
thiserror = {workspace = true }
uuid = {workspace = true }
url = {workspace = true}

