[package]
name = "bcr-wallet-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]

serde-wasm-bindgen.workspace = true
tokio_with_wasm = "0.8"
wasm-bindgen = "0.2"
js-sys = "0.3"
wasm-bindgen-futures = "0.4"
thiserror.workspace = true
serde.workspace = true
async-trait.workspace = true
reqwest = { workspace = true, features = ["json"] }
anyhow.workspace = true
rand.workspace = true
rexie.workspace = true
tracing.workspace = true
bitcoin.workspace = true
tracing-subscriber.workspace = true
tracing-wasm.workspace = true
getrandom = { version = "0.2.16", features = ["js"] }
# getrandom = { version = "0.3.3", features = ["wasm_js"] }
bip39.workspace = true
cashu = { workspace = true, default-features = false, features = ["wallet"] }
serde_json.workspace = true
ciborium.workspace = true
[dev-dependencies]
wasm-bindgen-test = { version = "0.3" }

[lib]
crate-type = ["cdylib", "rlib"]
