// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_app_state`, `init_logging`, `init_panic_hook`, `new`, `reset_runtime`, `start_jobs`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CurrencyUnit`, `WalletCleanLocalDbResponse`, `WalletRuntime`, `WalletsNamesResponse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`

Future<void> initWalletFfi({required WalletFfiConfig conf}) =>
    RustLib.instance.api.crateApiInitWalletFfi(conf: conf);

Future<AddWalletResponse> walletAdd() =>
    RustLib.instance.api.crateApiWalletAdd();

Future<RestoreWalletResponse> walletRestore() =>
    RustLib.instance.api.crateApiWalletRestore();

Future<void> walletDelete({required WalletRequest req}) =>
    RustLib.instance.api.crateApiWalletDelete(req: req);

Future<WalletNameResponse> walletGetName({required WalletRequest req}) =>
    RustLib.instance.api.crateApiWalletGetName(req: req);

Future<WalletMintUrlResponse> walletGetMintUrl({required WalletRequest req}) =>
    RustLib.instance.api.crateApiWalletGetMintUrl(req: req);

Future<WalletCurrencyUnitResponse> walletGetCurrencyUnit({
  required WalletRequest req,
}) => RustLib.instance.api.crateApiWalletGetCurrencyUnit(req: req);

Future<WalletBalanceResponse> walletGetBalance({required WalletRequest req}) =>
    RustLib.instance.api.crateApiWalletGetBalance(req: req);

Future<WalletTransactionIdResponse> walletReceive({
  required WalletReceiveRequest req,
}) => RustLib.instance.api.crateApiWalletReceive(req: req);

Future<WalletListRedemptionsResponse> walletListRedemptions({
  required WalletListRedemptionsRequest req,
}) => RustLib.instance.api.crateApiWalletListRedemptions(req: req);

Future<WalletTransactionResponse> walletLoadTransaction({
  required WalletTransactionRequest req,
}) => RustLib.instance.api.crateApiWalletLoadTransaction(req: req);

Future<WalletRefreshTransactionResponse> walletRefreshTransaction({
  required WalletRefreshTransactionRequest req,
}) => RustLib.instance.api.crateApiWalletRefreshTransaction(req: req);

Future<WalletRefreshTransactionsResponse> walletRefreshTransactions({
  required WalletRequest req,
}) => RustLib.instance.api.crateApiWalletRefreshTransactions(req: req);

Future<WalletReclaimTransactionResponse> walletReclaimTransaction({
  required WalletReclaimTransactionRequest req,
}) => RustLib.instance.api.crateApiWalletReclaimTransaction(req: req);

Future<WalletPreparePaymentResponse> walletPrepareMelt({
  required WalletPrepareMeltRequest req,
}) => RustLib.instance.api.crateApiWalletPrepareMelt(req: req);

Future<WalletTransactionIdResponse> walletMelt({
  required WalletPayRequest req,
}) => RustLib.instance.api.crateApiWalletMelt(req: req);

Future<WalletMintSummaryResponse> walletMint({
  required WalletMintRequest req,
}) => RustLib.instance.api.crateApiWalletMint(req: req);

Future<WalletPreparePaymentResponse> walletPreparePayment({
  required WalletPreparePaymentRequest req,
}) => RustLib.instance.api.crateApiWalletPreparePayment(req: req);

Future<WalletTransactionIdResponse> walletPay({
  required WalletPayRequest req,
}) => RustLib.instance.api.crateApiWalletPay(req: req);

Future<WalletPreparePaymentResponse> walletPreparePayByToken({
  required WalletPreparePaymentByTokenRequest req,
}) => RustLib.instance.api.crateApiWalletPreparePayByToken(req: req);

Future<WalletPaymentByTokenResponse> walletPayByToken({
  required WalletPaymentByTokenRequest req,
}) => RustLib.instance.api.crateApiWalletPayByToken(req: req);

Future<WalletPreparePaymentReqResponse> walletPreparePaymentRequest({
  required WalletPreparePaymentReqRequest req,
}) => RustLib.instance.api.crateApiWalletPreparePaymentRequest(req: req);

Future<WalletPaymentCheckHandle> walletCheckReceivedPayment({
  required WalletCheckReceivedPaymentRequest req,
  required FutureOr<void> Function(WalletMaybeTransactionIdResponse)
  resultCallback,
}) => RustLib.instance.api.crateApiWalletCheckReceivedPayment(
  req: req,
  resultCallback: resultCallback,
);

Future<WalletCheckPendingMintsResponse> walletCheckPendingMints({
  required WalletRequest req,
}) => RustLib.instance.api.crateApiWalletCheckPendingMints(req: req);

Future<WalletProtestMintResponse> walletProtestMint({
  required WalletProtestMintRequest req,
}) => RustLib.instance.api.crateApiWalletProtestMint(req: req);

Future<WalletProtestSwapResponse> walletProtestSwap({
  required WalletProtestSwapRequest req,
}) => RustLib.instance.api.crateApiWalletProtestSwap(req: req);

Future<WalletTransactionIdsResponse> walletGetTransactionIds({
  required WalletRequest req,
}) => RustLib.instance.api.crateApiWalletGetTransactionIds(req: req);

Future<WalletTransactionsResponse> walletGetTransactions({
  required WalletRequest req,
}) => RustLib.instance.api.crateApiWalletGetTransactions(req: req);

Future<WalletsIdsResponse> walletGetIds() =>
    RustLib.instance.api.crateApiWalletGetIds();

Future<MnemonicResponse> generateRandomMnemonic({
  required MnemonicRequest req,
}) => RustLib.instance.api.crateApiGenerateRandomMnemonic(req: req);

Future<IsValidTokenResponse> isValidToken({required IsValidTokenRequest req}) =>
    RustLib.instance.api.crateApiIsValidToken(req: req);

Future<WalletRedeemCreditResponse> walletRedeemCredit({
  required WalletRequest req,
}) => RustLib.instance.api.crateApiWalletRedeemCredit(req: req);

Future<StatusResponse> walletGetStatus() =>
    RustLib.instance.api.crateApiWalletGetStatus();

Future<MigrateRabidResponse> walletMigrateRabid() =>
    RustLib.instance.api.crateApiWalletMigrateRabid();

Future<MintIsOfflineResponse> walletMintIsOffline({
  required WalletRequest req,
}) => RustLib.instance.api.crateApiWalletMintIsOffline(req: req);

Future<MintIsRabidResponse> walletMintIsRabid({required WalletRequest req}) =>
    RustLib.instance.api.crateApiWalletMintIsRabid(req: req);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WalletPaymentCheckHandle>>
abstract class WalletPaymentCheckHandle implements RustOpaqueInterface {
  Future<void> cancel();
}

class AddWalletResponse {
  final BigInt walletId;

  const AddWalletResponse({required this.walletId});

  @override
  int get hashCode => walletId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddWalletResponse &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId;
}

class IsValidTokenRequest {
  final String token;

  const IsValidTokenRequest({required this.token});

  @override
  int get hashCode => token.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IsValidTokenRequest &&
          runtimeType == other.runtimeType &&
          token == other.token;
}

class IsValidTokenResponse {
  final BigInt amount;
  final String? memo;
  final String mintUrl;
  final String? unit;

  const IsValidTokenResponse({
    required this.amount,
    this.memo,
    required this.mintUrl,
    this.unit,
  });

  @override
  int get hashCode =>
      amount.hashCode ^ memo.hashCode ^ mintUrl.hashCode ^ unit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IsValidTokenResponse &&
          runtimeType == other.runtimeType &&
          amount == other.amount &&
          memo == other.memo &&
          mintUrl == other.mintUrl &&
          unit == other.unit;
}

class MeltTx {
  final String? alphaTxId;
  final String? betaTxId;

  const MeltTx({this.alphaTxId, this.betaTxId});

  @override
  int get hashCode => alphaTxId.hashCode ^ betaTxId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeltTx &&
          runtimeType == other.runtimeType &&
          alphaTxId == other.alphaTxId &&
          betaTxId == other.betaTxId;
}

class MigrateRabidResponse {
  final String? migratedToMint;

  const MigrateRabidResponse({this.migratedToMint});

  @override
  int get hashCode => migratedToMint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MigrateRabidResponse &&
          runtimeType == other.runtimeType &&
          migratedToMint == other.migratedToMint;
}

class MintIsOfflineResponse {
  final bool offline;

  const MintIsOfflineResponse({required this.offline});

  @override
  int get hashCode => offline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MintIsOfflineResponse &&
          runtimeType == other.runtimeType &&
          offline == other.offline;
}

class MintIsRabidResponse {
  final bool rabid;

  const MintIsRabidResponse({required this.rabid});

  @override
  int get hashCode => rabid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MintIsRabidResponse &&
          runtimeType == other.runtimeType &&
          rabid == other.rabid;
}

class MnemonicRequest {
  final int length;

  const MnemonicRequest({required this.length});

  @override
  int get hashCode => length.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MnemonicRequest &&
          runtimeType == other.runtimeType &&
          length == other.length;
}

class MnemonicResponse {
  final String mnemonic;

  const MnemonicResponse({required this.mnemonic});

  @override
  int get hashCode => mnemonic.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MnemonicResponse &&
          runtimeType == other.runtimeType &&
          mnemonic == other.mnemonic;
}

class PaymentRequest {
  final String request;
  final String pId;

  const PaymentRequest({required this.request, required this.pId});

  @override
  int get hashCode => request.hashCode ^ pId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaymentRequest &&
          runtimeType == other.runtimeType &&
          request == other.request &&
          pId == other.pId;
}

class PaymentSummary {
  final String requestId;
  final String unit;
  final BigInt amount;
  final BigInt fees;
  final BigInt reservedFees;
  final BigInt expiry;
  final PaymentType ptype;

  const PaymentSummary({
    required this.requestId,
    required this.unit,
    required this.amount,
    required this.fees,
    required this.reservedFees,
    required this.expiry,
    required this.ptype,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      unit.hashCode ^
      amount.hashCode ^
      fees.hashCode ^
      reservedFees.hashCode ^
      expiry.hashCode ^
      ptype.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaymentSummary &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          unit == other.unit &&
          amount == other.amount &&
          fees == other.fees &&
          reservedFees == other.reservedFees &&
          expiry == other.expiry &&
          ptype == other.ptype;
}

enum PaymentType {
  notApplicable,
  token,
  cdk18,
  onChain,
  swap;

  static Future<PaymentType> default_() =>
      RustLib.instance.api.crateApiPaymentTypeDefault();
}

enum ProtestStatus {
  resolved,
  rabid;

  static Future<ProtestStatus> default_() =>
      RustLib.instance.api.crateApiProtestStatusDefault();
}

class RedemptionSummary {
  final BigInt tstamp;
  final BigInt amount;

  const RedemptionSummary({required this.tstamp, required this.amount});

  @override
  int get hashCode => tstamp.hashCode ^ amount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RedemptionSummary &&
          runtimeType == other.runtimeType &&
          tstamp == other.tstamp &&
          amount == other.amount;
}

class RestoreWalletResponse {
  final BigInt walletId;

  const RestoreWalletResponse({required this.walletId});

  @override
  int get hashCode => walletId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RestoreWalletResponse &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId;
}

class StatusResponse {
  final String appVersion;

  const StatusResponse({required this.appVersion});

  @override
  int get hashCode => appVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatusResponse &&
          runtimeType == other.runtimeType &&
          appVersion == other.appVersion;
}

class Transaction {
  final String id;
  final BigInt amount;
  final BigInt fees;
  final String unit;
  final BigInt tstamp;
  final TransactionDirection direction;
  final String? memo;
  final PaymentType ptype;
  final TransactionStatus status;
  final MeltTx meltTx;
  final String? quoteId;

  const Transaction({
    required this.id,
    required this.amount,
    required this.fees,
    required this.unit,
    required this.tstamp,
    required this.direction,
    this.memo,
    required this.ptype,
    required this.status,
    required this.meltTx,
    this.quoteId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      amount.hashCode ^
      fees.hashCode ^
      unit.hashCode ^
      tstamp.hashCode ^
      direction.hashCode ^
      memo.hashCode ^
      ptype.hashCode ^
      status.hashCode ^
      meltTx.hashCode ^
      quoteId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Transaction &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          amount == other.amount &&
          fees == other.fees &&
          unit == other.unit &&
          tstamp == other.tstamp &&
          direction == other.direction &&
          memo == other.memo &&
          ptype == other.ptype &&
          status == other.status &&
          meltTx == other.meltTx &&
          quoteId == other.quoteId;
}

enum TransactionDirection {
  incoming,
  outgoing;

  static Future<TransactionDirection> default_() =>
      RustLib.instance.api.crateApiTransactionDirectionDefault();
}

enum TransactionStatus {
  notApplicable,
  pending,
  settled,
  canceled;

  static Future<TransactionStatus> default_() =>
      RustLib.instance.api.crateApiTransactionStatusDefault();
}

class WalletBalanceResponse {
  final BigInt debit;
  final BigInt credit;

  const WalletBalanceResponse({required this.debit, required this.credit});

  @override
  int get hashCode => debit.hashCode ^ credit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletBalanceResponse &&
          runtimeType == other.runtimeType &&
          debit == other.debit &&
          credit == other.credit;
}

class WalletCheckPendingMintsResponse {
  final List<String> txIds;

  const WalletCheckPendingMintsResponse({required this.txIds});

  @override
  int get hashCode => txIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletCheckPendingMintsResponse &&
          runtimeType == other.runtimeType &&
          txIds == other.txIds;
}

class WalletCheckReceivedPaymentRequest {
  final BigInt walletId;
  final BigInt maxWaitSec;
  final String pId;

  const WalletCheckReceivedPaymentRequest({
    required this.walletId,
    required this.maxWaitSec,
    required this.pId,
  });

  @override
  int get hashCode => walletId.hashCode ^ maxWaitSec.hashCode ^ pId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletCheckReceivedPaymentRequest &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId &&
          maxWaitSec == other.maxWaitSec &&
          pId == other.pId;
}

class WalletCurrencyUnitResponse {
  final String credit;
  final String debit;

  const WalletCurrencyUnitResponse({required this.credit, required this.debit});

  @override
  int get hashCode => credit.hashCode ^ debit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletCurrencyUnitResponse &&
          runtimeType == other.runtimeType &&
          credit == other.credit &&
          debit == other.debit;
}

class WalletError implements FrbException {
  final WalletErrorKind kind;
  final String msg;

  const WalletError({required this.kind, required this.msg});

  static Future<WalletError> badRequest({required String msg}) =>
      RustLib.instance.api.crateApiWalletErrorBadRequest(msg: msg);

  static Future<WalletError> internal() =>
      RustLib.instance.api.crateApiWalletErrorInternal();

  static Future<WalletError> network({required String msg}) =>
      RustLib.instance.api.crateApiWalletErrorNetwork(msg: msg);

  static Future<WalletError> notFound({required String msg}) =>
      RustLib.instance.api.crateApiWalletErrorNotFound(msg: msg);

  @override
  int get hashCode => kind.hashCode ^ msg.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          msg == other.msg;
}

enum WalletErrorKind {
  badRequest,
  notFound,
  network,
  internal,
  initialization,
  unsupported,
}

class WalletFfiConfig {
  final String dbFolderPath;
  final String logLevel;
  final BigInt jobIntervalSecs;
  final BigInt jobInitialDelaySecs;
  final String defaultMintUrl;
  final String bitcoinNetwork;
  final String mnemonic;
  final List<String> nostrRelays;
  final int swapExpiryMinutes;

  const WalletFfiConfig({
    required this.dbFolderPath,
    required this.logLevel,
    required this.jobIntervalSecs,
    required this.jobInitialDelaySecs,
    required this.defaultMintUrl,
    required this.bitcoinNetwork,
    required this.mnemonic,
    required this.nostrRelays,
    required this.swapExpiryMinutes,
  });

  @override
  int get hashCode =>
      dbFolderPath.hashCode ^
      logLevel.hashCode ^
      jobIntervalSecs.hashCode ^
      jobInitialDelaySecs.hashCode ^
      defaultMintUrl.hashCode ^
      bitcoinNetwork.hashCode ^
      mnemonic.hashCode ^
      nostrRelays.hashCode ^
      swapExpiryMinutes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletFfiConfig &&
          runtimeType == other.runtimeType &&
          dbFolderPath == other.dbFolderPath &&
          logLevel == other.logLevel &&
          jobIntervalSecs == other.jobIntervalSecs &&
          jobInitialDelaySecs == other.jobInitialDelaySecs &&
          defaultMintUrl == other.defaultMintUrl &&
          bitcoinNetwork == other.bitcoinNetwork &&
          mnemonic == other.mnemonic &&
          nostrRelays == other.nostrRelays &&
          swapExpiryMinutes == other.swapExpiryMinutes;
}

class WalletListRedemptionsRequest {
  final BigInt walletId;
  final BigInt paymentWindowSeconds;

  const WalletListRedemptionsRequest({
    required this.walletId,
    required this.paymentWindowSeconds,
  });

  @override
  int get hashCode => walletId.hashCode ^ paymentWindowSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletListRedemptionsRequest &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId &&
          paymentWindowSeconds == other.paymentWindowSeconds;
}

class WalletListRedemptionsResponse {
  final List<RedemptionSummary> redemptions;

  const WalletListRedemptionsResponse({required this.redemptions});

  @override
  int get hashCode => redemptions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletListRedemptionsResponse &&
          runtimeType == other.runtimeType &&
          redemptions == other.redemptions;
}

class WalletMaybeTransactionIdResponse {
  final String? txId;

  const WalletMaybeTransactionIdResponse({this.txId});

  @override
  int get hashCode => txId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletMaybeTransactionIdResponse &&
          runtimeType == other.runtimeType &&
          txId == other.txId;
}

class WalletMintRequest {
  final BigInt walletId;
  final BigInt amount;

  const WalletMintRequest({required this.walletId, required this.amount});

  @override
  int get hashCode => walletId.hashCode ^ amount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletMintRequest &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId &&
          amount == other.amount;
}

class WalletMintSummaryResponse {
  final String quoteId;
  final BigInt amount;
  final String address;
  final BigInt expiry;

  const WalletMintSummaryResponse({
    required this.quoteId,
    required this.amount,
    required this.address,
    required this.expiry,
  });

  @override
  int get hashCode =>
      quoteId.hashCode ^ amount.hashCode ^ address.hashCode ^ expiry.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletMintSummaryResponse &&
          runtimeType == other.runtimeType &&
          quoteId == other.quoteId &&
          amount == other.amount &&
          address == other.address &&
          expiry == other.expiry;
}

class WalletMintUrlResponse {
  final String mintUrl;

  const WalletMintUrlResponse({required this.mintUrl});

  @override
  int get hashCode => mintUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletMintUrlResponse &&
          runtimeType == other.runtimeType &&
          mintUrl == other.mintUrl;
}

class WalletNameResponse {
  final String name;

  const WalletNameResponse({required this.name});

  @override
  int get hashCode => name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletNameResponse &&
          runtimeType == other.runtimeType &&
          name == other.name;
}

class WalletPayRequest {
  final BigInt walletId;
  final String rid;

  const WalletPayRequest({required this.walletId, required this.rid});

  @override
  int get hashCode => walletId.hashCode ^ rid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletPayRequest &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId &&
          rid == other.rid;
}

class WalletPaymentByTokenRequest {
  final BigInt walletId;
  final String rid;

  const WalletPaymentByTokenRequest({
    required this.walletId,
    required this.rid,
  });

  @override
  int get hashCode => walletId.hashCode ^ rid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletPaymentByTokenRequest &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId &&
          rid == other.rid;
}

class WalletPaymentByTokenResponse {
  final String txId;
  final String token;

  const WalletPaymentByTokenResponse({required this.txId, required this.token});

  @override
  int get hashCode => txId.hashCode ^ token.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletPaymentByTokenResponse &&
          runtimeType == other.runtimeType &&
          txId == other.txId &&
          token == other.token;
}

class WalletPrepareMeltRequest {
  final BigInt walletId;
  final BigInt amount;
  final String address;
  final String? description;

  const WalletPrepareMeltRequest({
    required this.walletId,
    required this.amount,
    required this.address,
    this.description,
  });

  @override
  int get hashCode =>
      walletId.hashCode ^
      amount.hashCode ^
      address.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletPrepareMeltRequest &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId &&
          amount == other.amount &&
          address == other.address &&
          description == other.description;
}

class WalletPreparePaymentByTokenRequest {
  final BigInt walletId;
  final BigInt amount;
  final String unit;
  final String? description;

  const WalletPreparePaymentByTokenRequest({
    required this.walletId,
    required this.amount,
    required this.unit,
    this.description,
  });

  @override
  int get hashCode =>
      walletId.hashCode ^
      amount.hashCode ^
      unit.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletPreparePaymentByTokenRequest &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId &&
          amount == other.amount &&
          unit == other.unit &&
          description == other.description;
}

class WalletPreparePaymentReqRequest {
  final BigInt walletId;
  final BigInt amount;
  final String unit;
  final String? description;

  const WalletPreparePaymentReqRequest({
    required this.walletId,
    required this.amount,
    required this.unit,
    this.description,
  });

  @override
  int get hashCode =>
      walletId.hashCode ^
      amount.hashCode ^
      unit.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletPreparePaymentReqRequest &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId &&
          amount == other.amount &&
          unit == other.unit &&
          description == other.description;
}

class WalletPreparePaymentReqResponse {
  final PaymentRequest paymentRequest;

  const WalletPreparePaymentReqResponse({required this.paymentRequest});

  @override
  int get hashCode => paymentRequest.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletPreparePaymentReqResponse &&
          runtimeType == other.runtimeType &&
          paymentRequest == other.paymentRequest;
}

class WalletPreparePaymentRequest {
  final BigInt walletId;
  final String input;

  const WalletPreparePaymentRequest({
    required this.walletId,
    required this.input,
  });

  @override
  int get hashCode => walletId.hashCode ^ input.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletPreparePaymentRequest &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId &&
          input == other.input;
}

class WalletPreparePaymentResponse {
  final PaymentSummary paymentSummary;

  const WalletPreparePaymentResponse({required this.paymentSummary});

  @override
  int get hashCode => paymentSummary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletPreparePaymentResponse &&
          runtimeType == other.runtimeType &&
          paymentSummary == other.paymentSummary;
}

class WalletProtestMintRequest {
  final BigInt walletId;
  final String quoteId;

  const WalletProtestMintRequest({
    required this.walletId,
    required this.quoteId,
  });

  @override
  int get hashCode => walletId.hashCode ^ quoteId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletProtestMintRequest &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId &&
          quoteId == other.quoteId;
}

class WalletProtestMintResponse {
  final ProtestStatus status;
  final BigInt? amount;

  const WalletProtestMintResponse({required this.status, this.amount});

  @override
  int get hashCode => status.hashCode ^ amount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletProtestMintResponse &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          amount == other.amount;
}

class WalletProtestSwapRequest {
  final BigInt walletId;
  final String commitmentSig;

  const WalletProtestSwapRequest({
    required this.walletId,
    required this.commitmentSig,
  });

  @override
  int get hashCode => walletId.hashCode ^ commitmentSig.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletProtestSwapRequest &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId &&
          commitmentSig == other.commitmentSig;
}

class WalletProtestSwapResponse {
  final ProtestStatus status;
  final BigInt? amount;

  const WalletProtestSwapResponse({required this.status, this.amount});

  @override
  int get hashCode => status.hashCode ^ amount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletProtestSwapResponse &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          amount == other.amount;
}

class WalletReceiveRequest {
  final BigInt walletId;
  final String token;

  const WalletReceiveRequest({required this.walletId, required this.token});

  @override
  int get hashCode => walletId.hashCode ^ token.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletReceiveRequest &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId &&
          token == other.token;
}

class WalletReclaimTransactionRequest {
  final BigInt walletId;
  final String txId;

  const WalletReclaimTransactionRequest({
    required this.walletId,
    required this.txId,
  });

  @override
  int get hashCode => walletId.hashCode ^ txId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletReclaimTransactionRequest &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId &&
          txId == other.txId;
}

class WalletReclaimTransactionResponse {
  final BigInt amount;

  const WalletReclaimTransactionResponse({required this.amount});

  @override
  int get hashCode => amount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletReclaimTransactionResponse &&
          runtimeType == other.runtimeType &&
          amount == other.amount;
}

class WalletRedeemCreditResponse {
  final BigInt amount;

  const WalletRedeemCreditResponse({required this.amount});

  @override
  int get hashCode => amount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletRedeemCreditResponse &&
          runtimeType == other.runtimeType &&
          amount == other.amount;
}

class WalletRefreshTransactionRequest {
  final BigInt walletId;
  final String txId;

  const WalletRefreshTransactionRequest({
    required this.walletId,
    required this.txId,
  });

  @override
  int get hashCode => walletId.hashCode ^ txId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletRefreshTransactionRequest &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId &&
          txId == other.txId;
}

class WalletRefreshTransactionResponse {
  final bool updated;

  const WalletRefreshTransactionResponse({required this.updated});

  @override
  int get hashCode => updated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletRefreshTransactionResponse &&
          runtimeType == other.runtimeType &&
          updated == other.updated;
}

class WalletRefreshTransactionsResponse {
  final BigInt updated;

  const WalletRefreshTransactionsResponse({required this.updated});

  @override
  int get hashCode => updated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletRefreshTransactionsResponse &&
          runtimeType == other.runtimeType &&
          updated == other.updated;
}

class WalletRequest {
  final BigInt walletId;

  const WalletRequest({required this.walletId});

  @override
  int get hashCode => walletId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletRequest &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId;
}

class WalletTransactionIdResponse {
  final String txId;

  const WalletTransactionIdResponse({required this.txId});

  @override
  int get hashCode => txId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletTransactionIdResponse &&
          runtimeType == other.runtimeType &&
          txId == other.txId;
}

class WalletTransactionIdsResponse {
  final List<String> txIds;

  const WalletTransactionIdsResponse({required this.txIds});

  @override
  int get hashCode => txIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletTransactionIdsResponse &&
          runtimeType == other.runtimeType &&
          txIds == other.txIds;
}

class WalletTransactionRequest {
  final BigInt walletId;
  final String txId;

  const WalletTransactionRequest({required this.walletId, required this.txId});

  @override
  int get hashCode => walletId.hashCode ^ txId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletTransactionRequest &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId &&
          txId == other.txId;
}

class WalletTransactionResponse {
  final Transaction transaction;

  const WalletTransactionResponse({required this.transaction});

  @override
  int get hashCode => transaction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletTransactionResponse &&
          runtimeType == other.runtimeType &&
          transaction == other.transaction;
}

class WalletTransactionsResponse {
  final List<Transaction> txs;

  const WalletTransactionsResponse({required this.txs});

  @override
  int get hashCode => txs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletTransactionsResponse &&
          runtimeType == other.runtimeType &&
          txs == other.txs;
}

class WalletsIdsResponse {
  final Uint64List ids;

  const WalletsIdsResponse({required this.ids});

  @override
  int get hashCode => ids.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletsIdsResponse &&
          runtimeType == other.runtimeType &&
          ids == other.ids;
}
