// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_WalletPaymentCheckHandlePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPaymentCheckHandlePtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  WalletPaymentCheckHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPaymentCheckHandle(
    dynamic raw,
  );

  @protected
  WalletPaymentCheckHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPaymentCheckHandle(
    dynamic raw,
  );

  @protected
  FutureOr<void> Function(WalletMaybeTransactionIdResponse)
  dco_decode_DartFn_Inputs_wallet_maybe_transaction_id_response_Output_unit_AnyhowException(
    dynamic raw,
  );

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  WalletPaymentCheckHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPaymentCheckHandle(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AddWalletResponse dco_decode_add_wallet_response(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  IsValidTokenRequest dco_decode_box_autoadd_is_valid_token_request(
    dynamic raw,
  );

  @protected
  MnemonicRequest dco_decode_box_autoadd_mnemonic_request(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  WalletCheckReceivedPaymentRequest
  dco_decode_box_autoadd_wallet_check_received_payment_request(dynamic raw);

  @protected
  WalletFfiConfig dco_decode_box_autoadd_wallet_ffi_config(dynamic raw);

  @protected
  WalletMintRequest dco_decode_box_autoadd_wallet_mint_request(dynamic raw);

  @protected
  WalletPayRequest dco_decode_box_autoadd_wallet_pay_request(dynamic raw);

  @protected
  WalletPaymentByTokenRequest
  dco_decode_box_autoadd_wallet_payment_by_token_request(dynamic raw);

  @protected
  WalletPrepareMeltRequest dco_decode_box_autoadd_wallet_prepare_melt_request(
    dynamic raw,
  );

  @protected
  WalletPreparePaymentByTokenRequest
  dco_decode_box_autoadd_wallet_prepare_payment_by_token_request(dynamic raw);

  @protected
  WalletPreparePaymentReqRequest
  dco_decode_box_autoadd_wallet_prepare_payment_req_request(dynamic raw);

  @protected
  WalletPreparePaymentRequest
  dco_decode_box_autoadd_wallet_prepare_payment_request(dynamic raw);

  @protected
  WalletProtestMeltRequest dco_decode_box_autoadd_wallet_protest_melt_request(
    dynamic raw,
  );

  @protected
  WalletProtestMintRequest dco_decode_box_autoadd_wallet_protest_mint_request(
    dynamic raw,
  );

  @protected
  WalletProtestSwapRequest dco_decode_box_autoadd_wallet_protest_swap_request(
    dynamic raw,
  );

  @protected
  WalletReceiveRequest dco_decode_box_autoadd_wallet_receive_request(
    dynamic raw,
  );

  @protected
  WalletReclaimTransactionRequest
  dco_decode_box_autoadd_wallet_reclaim_transaction_request(dynamic raw);

  @protected
  WalletRefreshTransactionRequest
  dco_decode_box_autoadd_wallet_refresh_transaction_request(dynamic raw);

  @protected
  WalletRequest dco_decode_box_autoadd_wallet_request(dynamic raw);

  @protected
  WalletTransactionRequest dco_decode_box_autoadd_wallet_transaction_request(
    dynamic raw,
  );

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  IsValidTokenRequest dco_decode_is_valid_token_request(dynamic raw);

  @protected
  IsValidTokenResponse dco_decode_is_valid_token_response(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_usize_strict(dynamic raw);

  @protected
  List<Transaction> dco_decode_list_transaction(dynamic raw);

  @protected
  List<WalletDevModeDetailedBalanceEntry>
  dco_decode_list_wallet_dev_mode_detailed_balance_entry(dynamic raw);

  @protected
  MeltTx dco_decode_melt_tx(dynamic raw);

  @protected
  MigrateRabidResponse dco_decode_migrate_rabid_response(dynamic raw);

  @protected
  MintIsOfflineResponse dco_decode_mint_is_offline_response(dynamic raw);

  @protected
  MintIsRabidResponse dco_decode_mint_is_rabid_response(dynamic raw);

  @protected
  MnemonicRequest dco_decode_mnemonic_request(dynamic raw);

  @protected
  MnemonicResponse dco_decode_mnemonic_response(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  PaymentRequest dco_decode_payment_request(dynamic raw);

  @protected
  PaymentSummary dco_decode_payment_summary(dynamic raw);

  @protected
  PaymentType dco_decode_payment_type(dynamic raw);

  @protected
  ProtestStatus dco_decode_protest_status(dynamic raw);

  @protected
  RestoreWalletResponse dco_decode_restore_wallet_response(dynamic raw);

  @protected
  StatusResponse dco_decode_status_response(dynamic raw);

  @protected
  Transaction dco_decode_transaction(dynamic raw);

  @protected
  TransactionDirection dco_decode_transaction_direction(dynamic raw);

  @protected
  TransactionStatus dco_decode_transaction_status(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WalletBalanceResponse dco_decode_wallet_balance_response(dynamic raw);

  @protected
  WalletCheckPendingMintsResponse
  dco_decode_wallet_check_pending_mints_response(dynamic raw);

  @protected
  WalletCheckReceivedPaymentRequest
  dco_decode_wallet_check_received_payment_request(dynamic raw);

  @protected
  WalletCurrencyUnitResponse dco_decode_wallet_currency_unit_response(
    dynamic raw,
  );

  @protected
  WalletDevModeDetailedBalanceEntry
  dco_decode_wallet_dev_mode_detailed_balance_entry(dynamic raw);

  @protected
  WalletDevModeDetailedBalanceResponse
  dco_decode_wallet_dev_mode_detailed_balance_response(dynamic raw);

  @protected
  WalletError dco_decode_wallet_error(dynamic raw);

  @protected
  WalletErrorKind dco_decode_wallet_error_kind(dynamic raw);

  @protected
  WalletFfiConfig dco_decode_wallet_ffi_config(dynamic raw);

  @protected
  WalletMaybeTransactionIdResponse
  dco_decode_wallet_maybe_transaction_id_response(dynamic raw);

  @protected
  WalletMintRequest dco_decode_wallet_mint_request(dynamic raw);

  @protected
  WalletMintSummaryResponse dco_decode_wallet_mint_summary_response(
    dynamic raw,
  );

  @protected
  WalletMintUrlResponse dco_decode_wallet_mint_url_response(dynamic raw);

  @protected
  WalletNameResponse dco_decode_wallet_name_response(dynamic raw);

  @protected
  WalletPayRequest dco_decode_wallet_pay_request(dynamic raw);

  @protected
  WalletPaymentByTokenRequest dco_decode_wallet_payment_by_token_request(
    dynamic raw,
  );

  @protected
  WalletPaymentByTokenResponse dco_decode_wallet_payment_by_token_response(
    dynamic raw,
  );

  @protected
  WalletPrepareMeltRequest dco_decode_wallet_prepare_melt_request(dynamic raw);

  @protected
  WalletPreparePaymentByTokenRequest
  dco_decode_wallet_prepare_payment_by_token_request(dynamic raw);

  @protected
  WalletPreparePaymentReqRequest dco_decode_wallet_prepare_payment_req_request(
    dynamic raw,
  );

  @protected
  WalletPreparePaymentReqResponse
  dco_decode_wallet_prepare_payment_req_response(dynamic raw);

  @protected
  WalletPreparePaymentRequest dco_decode_wallet_prepare_payment_request(
    dynamic raw,
  );

  @protected
  WalletPreparePaymentResponse dco_decode_wallet_prepare_payment_response(
    dynamic raw,
  );

  @protected
  WalletProtestMeltRequest dco_decode_wallet_protest_melt_request(dynamic raw);

  @protected
  WalletProtestMeltResponse dco_decode_wallet_protest_melt_response(
    dynamic raw,
  );

  @protected
  WalletProtestMintRequest dco_decode_wallet_protest_mint_request(dynamic raw);

  @protected
  WalletProtestMintResponse dco_decode_wallet_protest_mint_response(
    dynamic raw,
  );

  @protected
  WalletProtestSwapRequest dco_decode_wallet_protest_swap_request(dynamic raw);

  @protected
  WalletProtestSwapResponse dco_decode_wallet_protest_swap_response(
    dynamic raw,
  );

  @protected
  WalletReceiveRequest dco_decode_wallet_receive_request(dynamic raw);

  @protected
  WalletReclaimTransactionRequest dco_decode_wallet_reclaim_transaction_request(
    dynamic raw,
  );

  @protected
  WalletReclaimTransactionResponse
  dco_decode_wallet_reclaim_transaction_response(dynamic raw);

  @protected
  WalletRecoverStaleTransactionResponse
  dco_decode_wallet_recover_stale_transaction_response(dynamic raw);

  @protected
  WalletRefreshTransactionRequest dco_decode_wallet_refresh_transaction_request(
    dynamic raw,
  );

  @protected
  WalletRefreshTransactionResponse
  dco_decode_wallet_refresh_transaction_response(dynamic raw);

  @protected
  WalletRefreshTransactionsResponse
  dco_decode_wallet_refresh_transactions_response(dynamic raw);

  @protected
  WalletRequest dco_decode_wallet_request(dynamic raw);

  @protected
  WalletTransactionIdResponse dco_decode_wallet_transaction_id_response(
    dynamic raw,
  );

  @protected
  WalletTransactionIdsResponse dco_decode_wallet_transaction_ids_response(
    dynamic raw,
  );

  @protected
  WalletTransactionRequest dco_decode_wallet_transaction_request(dynamic raw);

  @protected
  WalletTransactionResponse dco_decode_wallet_transaction_response(dynamic raw);

  @protected
  WalletTransactionsResponse dco_decode_wallet_transactions_response(
    dynamic raw,
  );

  @protected
  WalletsIdsResponse dco_decode_wallets_ids_response(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  WalletPaymentCheckHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPaymentCheckHandle(
    SseDeserializer deserializer,
  );

  @protected
  WalletPaymentCheckHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPaymentCheckHandle(
    SseDeserializer deserializer,
  );

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  WalletPaymentCheckHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPaymentCheckHandle(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AddWalletResponse sse_decode_add_wallet_response(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  IsValidTokenRequest sse_decode_box_autoadd_is_valid_token_request(
    SseDeserializer deserializer,
  );

  @protected
  MnemonicRequest sse_decode_box_autoadd_mnemonic_request(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  WalletCheckReceivedPaymentRequest
  sse_decode_box_autoadd_wallet_check_received_payment_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletFfiConfig sse_decode_box_autoadd_wallet_ffi_config(
    SseDeserializer deserializer,
  );

  @protected
  WalletMintRequest sse_decode_box_autoadd_wallet_mint_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletPayRequest sse_decode_box_autoadd_wallet_pay_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletPaymentByTokenRequest
  sse_decode_box_autoadd_wallet_payment_by_token_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletPrepareMeltRequest sse_decode_box_autoadd_wallet_prepare_melt_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletPreparePaymentByTokenRequest
  sse_decode_box_autoadd_wallet_prepare_payment_by_token_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletPreparePaymentReqRequest
  sse_decode_box_autoadd_wallet_prepare_payment_req_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletPreparePaymentRequest
  sse_decode_box_autoadd_wallet_prepare_payment_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletProtestMeltRequest sse_decode_box_autoadd_wallet_protest_melt_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletProtestMintRequest sse_decode_box_autoadd_wallet_protest_mint_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletProtestSwapRequest sse_decode_box_autoadd_wallet_protest_swap_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletReceiveRequest sse_decode_box_autoadd_wallet_receive_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletReclaimTransactionRequest
  sse_decode_box_autoadd_wallet_reclaim_transaction_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletRefreshTransactionRequest
  sse_decode_box_autoadd_wallet_refresh_transaction_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletRequest sse_decode_box_autoadd_wallet_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletTransactionRequest sse_decode_box_autoadd_wallet_transaction_request(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  IsValidTokenRequest sse_decode_is_valid_token_request(
    SseDeserializer deserializer,
  );

  @protected
  IsValidTokenResponse sse_decode_is_valid_token_response(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_usize_strict(SseDeserializer deserializer);

  @protected
  List<Transaction> sse_decode_list_transaction(SseDeserializer deserializer);

  @protected
  List<WalletDevModeDetailedBalanceEntry>
  sse_decode_list_wallet_dev_mode_detailed_balance_entry(
    SseDeserializer deserializer,
  );

  @protected
  MeltTx sse_decode_melt_tx(SseDeserializer deserializer);

  @protected
  MigrateRabidResponse sse_decode_migrate_rabid_response(
    SseDeserializer deserializer,
  );

  @protected
  MintIsOfflineResponse sse_decode_mint_is_offline_response(
    SseDeserializer deserializer,
  );

  @protected
  MintIsRabidResponse sse_decode_mint_is_rabid_response(
    SseDeserializer deserializer,
  );

  @protected
  MnemonicRequest sse_decode_mnemonic_request(SseDeserializer deserializer);

  @protected
  MnemonicResponse sse_decode_mnemonic_response(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  PaymentRequest sse_decode_payment_request(SseDeserializer deserializer);

  @protected
  PaymentSummary sse_decode_payment_summary(SseDeserializer deserializer);

  @protected
  PaymentType sse_decode_payment_type(SseDeserializer deserializer);

  @protected
  ProtestStatus sse_decode_protest_status(SseDeserializer deserializer);

  @protected
  RestoreWalletResponse sse_decode_restore_wallet_response(
    SseDeserializer deserializer,
  );

  @protected
  StatusResponse sse_decode_status_response(SseDeserializer deserializer);

  @protected
  Transaction sse_decode_transaction(SseDeserializer deserializer);

  @protected
  TransactionDirection sse_decode_transaction_direction(
    SseDeserializer deserializer,
  );

  @protected
  TransactionStatus sse_decode_transaction_status(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WalletBalanceResponse sse_decode_wallet_balance_response(
    SseDeserializer deserializer,
  );

  @protected
  WalletCheckPendingMintsResponse
  sse_decode_wallet_check_pending_mints_response(SseDeserializer deserializer);

  @protected
  WalletCheckReceivedPaymentRequest
  sse_decode_wallet_check_received_payment_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletCurrencyUnitResponse sse_decode_wallet_currency_unit_response(
    SseDeserializer deserializer,
  );

  @protected
  WalletDevModeDetailedBalanceEntry
  sse_decode_wallet_dev_mode_detailed_balance_entry(
    SseDeserializer deserializer,
  );

  @protected
  WalletDevModeDetailedBalanceResponse
  sse_decode_wallet_dev_mode_detailed_balance_response(
    SseDeserializer deserializer,
  );

  @protected
  WalletError sse_decode_wallet_error(SseDeserializer deserializer);

  @protected
  WalletErrorKind sse_decode_wallet_error_kind(SseDeserializer deserializer);

  @protected
  WalletFfiConfig sse_decode_wallet_ffi_config(SseDeserializer deserializer);

  @protected
  WalletMaybeTransactionIdResponse
  sse_decode_wallet_maybe_transaction_id_response(SseDeserializer deserializer);

  @protected
  WalletMintRequest sse_decode_wallet_mint_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletMintSummaryResponse sse_decode_wallet_mint_summary_response(
    SseDeserializer deserializer,
  );

  @protected
  WalletMintUrlResponse sse_decode_wallet_mint_url_response(
    SseDeserializer deserializer,
  );

  @protected
  WalletNameResponse sse_decode_wallet_name_response(
    SseDeserializer deserializer,
  );

  @protected
  WalletPayRequest sse_decode_wallet_pay_request(SseDeserializer deserializer);

  @protected
  WalletPaymentByTokenRequest sse_decode_wallet_payment_by_token_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletPaymentByTokenResponse sse_decode_wallet_payment_by_token_response(
    SseDeserializer deserializer,
  );

  @protected
  WalletPrepareMeltRequest sse_decode_wallet_prepare_melt_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletPreparePaymentByTokenRequest
  sse_decode_wallet_prepare_payment_by_token_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletPreparePaymentReqRequest sse_decode_wallet_prepare_payment_req_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletPreparePaymentReqResponse
  sse_decode_wallet_prepare_payment_req_response(SseDeserializer deserializer);

  @protected
  WalletPreparePaymentRequest sse_decode_wallet_prepare_payment_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletPreparePaymentResponse sse_decode_wallet_prepare_payment_response(
    SseDeserializer deserializer,
  );

  @protected
  WalletProtestMeltRequest sse_decode_wallet_protest_melt_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletProtestMeltResponse sse_decode_wallet_protest_melt_response(
    SseDeserializer deserializer,
  );

  @protected
  WalletProtestMintRequest sse_decode_wallet_protest_mint_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletProtestMintResponse sse_decode_wallet_protest_mint_response(
    SseDeserializer deserializer,
  );

  @protected
  WalletProtestSwapRequest sse_decode_wallet_protest_swap_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletProtestSwapResponse sse_decode_wallet_protest_swap_response(
    SseDeserializer deserializer,
  );

  @protected
  WalletReceiveRequest sse_decode_wallet_receive_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletReclaimTransactionRequest sse_decode_wallet_reclaim_transaction_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletReclaimTransactionResponse
  sse_decode_wallet_reclaim_transaction_response(SseDeserializer deserializer);

  @protected
  WalletRecoverStaleTransactionResponse
  sse_decode_wallet_recover_stale_transaction_response(
    SseDeserializer deserializer,
  );

  @protected
  WalletRefreshTransactionRequest sse_decode_wallet_refresh_transaction_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletRefreshTransactionResponse
  sse_decode_wallet_refresh_transaction_response(SseDeserializer deserializer);

  @protected
  WalletRefreshTransactionsResponse
  sse_decode_wallet_refresh_transactions_response(SseDeserializer deserializer);

  @protected
  WalletRequest sse_decode_wallet_request(SseDeserializer deserializer);

  @protected
  WalletTransactionIdResponse sse_decode_wallet_transaction_id_response(
    SseDeserializer deserializer,
  );

  @protected
  WalletTransactionIdsResponse sse_decode_wallet_transaction_ids_response(
    SseDeserializer deserializer,
  );

  @protected
  WalletTransactionRequest sse_decode_wallet_transaction_request(
    SseDeserializer deserializer,
  );

  @protected
  WalletTransactionResponse sse_decode_wallet_transaction_response(
    SseDeserializer deserializer,
  );

  @protected
  WalletTransactionsResponse sse_decode_wallet_transactions_response(
    SseDeserializer deserializer,
  );

  @protected
  WalletsIdsResponse sse_decode_wallets_ids_response(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPaymentCheckHandle(
    WalletPaymentCheckHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPaymentCheckHandle(
    WalletPaymentCheckHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_wallet_maybe_transaction_id_response_Output_unit_AnyhowException(
    FutureOr<void> Function(WalletMaybeTransactionIdResponse) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPaymentCheckHandle(
    WalletPaymentCheckHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_add_wallet_response(
    AddWalletResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_is_valid_token_request(
    IsValidTokenRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mnemonic_request(
    MnemonicRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_wallet_check_received_payment_request(
    WalletCheckReceivedPaymentRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wallet_ffi_config(
    WalletFfiConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wallet_mint_request(
    WalletMintRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wallet_pay_request(
    WalletPayRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wallet_payment_by_token_request(
    WalletPaymentByTokenRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wallet_prepare_melt_request(
    WalletPrepareMeltRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wallet_prepare_payment_by_token_request(
    WalletPreparePaymentByTokenRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wallet_prepare_payment_req_request(
    WalletPreparePaymentReqRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wallet_prepare_payment_request(
    WalletPreparePaymentRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wallet_protest_melt_request(
    WalletProtestMeltRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wallet_protest_mint_request(
    WalletProtestMintRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wallet_protest_swap_request(
    WalletProtestSwapRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wallet_receive_request(
    WalletReceiveRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wallet_reclaim_transaction_request(
    WalletReclaimTransactionRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wallet_refresh_transaction_request(
    WalletRefreshTransactionRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wallet_request(
    WalletRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wallet_transaction_request(
    WalletTransactionRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_is_valid_token_request(
    IsValidTokenRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_is_valid_token_response(
    IsValidTokenResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_usize_strict(
    Uint64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transaction(
    List<Transaction> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_wallet_dev_mode_detailed_balance_entry(
    List<WalletDevModeDetailedBalanceEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_melt_tx(MeltTx self, SseSerializer serializer);

  @protected
  void sse_encode_migrate_rabid_response(
    MigrateRabidResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mint_is_offline_response(
    MintIsOfflineResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mint_is_rabid_response(
    MintIsRabidResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mnemonic_request(
    MnemonicRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mnemonic_response(
    MnemonicResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_payment_request(
    PaymentRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_payment_summary(
    PaymentSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_payment_type(PaymentType self, SseSerializer serializer);

  @protected
  void sse_encode_protest_status(ProtestStatus self, SseSerializer serializer);

  @protected
  void sse_encode_restore_wallet_response(
    RestoreWalletResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_status_response(
    StatusResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transaction(Transaction self, SseSerializer serializer);

  @protected
  void sse_encode_transaction_direction(
    TransactionDirection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transaction_status(
    TransactionStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_balance_response(
    WalletBalanceResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_check_pending_mints_response(
    WalletCheckPendingMintsResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_check_received_payment_request(
    WalletCheckReceivedPaymentRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_currency_unit_response(
    WalletCurrencyUnitResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_dev_mode_detailed_balance_entry(
    WalletDevModeDetailedBalanceEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_dev_mode_detailed_balance_response(
    WalletDevModeDetailedBalanceResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_error(WalletError self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_error_kind(
    WalletErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_ffi_config(
    WalletFfiConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_maybe_transaction_id_response(
    WalletMaybeTransactionIdResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_mint_request(
    WalletMintRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_mint_summary_response(
    WalletMintSummaryResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_mint_url_response(
    WalletMintUrlResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_name_response(
    WalletNameResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_pay_request(
    WalletPayRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_payment_by_token_request(
    WalletPaymentByTokenRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_payment_by_token_response(
    WalletPaymentByTokenResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_prepare_melt_request(
    WalletPrepareMeltRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_prepare_payment_by_token_request(
    WalletPreparePaymentByTokenRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_prepare_payment_req_request(
    WalletPreparePaymentReqRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_prepare_payment_req_response(
    WalletPreparePaymentReqResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_prepare_payment_request(
    WalletPreparePaymentRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_prepare_payment_response(
    WalletPreparePaymentResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_protest_melt_request(
    WalletProtestMeltRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_protest_melt_response(
    WalletProtestMeltResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_protest_mint_request(
    WalletProtestMintRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_protest_mint_response(
    WalletProtestMintResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_protest_swap_request(
    WalletProtestSwapRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_protest_swap_response(
    WalletProtestSwapResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_receive_request(
    WalletReceiveRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_reclaim_transaction_request(
    WalletReclaimTransactionRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_reclaim_transaction_response(
    WalletReclaimTransactionResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_recover_stale_transaction_response(
    WalletRecoverStaleTransactionResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_refresh_transaction_request(
    WalletRefreshTransactionRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_refresh_transaction_response(
    WalletRefreshTransactionResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_refresh_transactions_response(
    WalletRefreshTransactionsResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_request(WalletRequest self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_transaction_id_response(
    WalletTransactionIdResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_transaction_ids_response(
    WalletTransactionIdsResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_transaction_request(
    WalletTransactionRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_transaction_response(
    WalletTransactionResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_transactions_response(
    WalletTransactionsResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallets_ids_response(
    WalletsIdsResponse self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPaymentCheckHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPaymentCheckHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPaymentCheckHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_wallet_ffi_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPaymentCheckHandle',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPaymentCheckHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPaymentCheckHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPaymentCheckHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPaymentCheckHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPaymentCheckHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_wallet_ffi_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPaymentCheckHandle',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPaymentCheckHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPaymentCheckHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
