# mint_url = "http://localhost:8080"
# mint_url = "https://mint.wildcat0.clowder1.minibill.tech"
mint_url = "https://mint.wildcat0.clowder-dev.minibill.tech"
mnemonic = "royal scheme canoe flame sell jewel valve citizen deal patch stereo walk"
log_level = "DEBUG"
db_path = "./alice.db"
network = "testnet"
nostr_relays = ["wss://relay.wildcat0.clowder-dev.minibill.tech"]
