# mint_url = "https://mint.wildcat0.clowder1.minibill.tech"
mint_url = "https://wildcat-dev-docker.minibill.tech"
mnemonic = "trip piano round arrest seven kangaroo used critic museum decline erupt horse"
log_level = "DEBUG"
db_path = "./bob.db"
